import type { NextPage } from 'next'
import Head from 'next/head'
import Theatre from '../src/Components/Theatre'
import Layout from '../src/Layout/Layout'
import image_ from '../public/images/image_.png'
import chair from '../public/images/chair.png'
import certain from '../public/images/certain.png'
import Postanovki from '../src/Components/Postanovki'
import musem from '../public/images/musem.png'
import statue from '../public/images/statue.png'
import fantan from '../public/images/fantan.png'
import theatre from '../public/images/theatre.png'
import stars from '../public/images/stars.png'
import gaz from '../public/images/gaz.png'
import Partners from '../src/Components/Partners'

const Home: NextPage = () => {
  const text: string = 'Как свидетельствуют архивные документы, первое каменное здание Большого театра начали возводить в 1775 году по проекту Антонио Ринальди. В дальнейшем, после того как Ринальди упал с лесов и не мог лично наблюдать за ходом работ, Екатерина II поручила немецкому театральному декоратору и архитектору Людвигу Филиппу Тишбейну создать новый проект театра, который и был воплощён архитекторами Ф. В. фон Бауром и М. А. Деденёвым. Открытие его состоялось в 1783 году, хотя, основываясь на других свидетельствах, годом открытия можно считать 1784 год.'
  const image: string = image_.src
  const image2: string = chair.src
  const image3: string = certain.src
  const image4: string = musem.src
  const image5: string = statue.src
  const image6: string = fantan.src
  const image7: string = theatre.src
  const star: string = stars.src
  const gazprom: string = gaz.src
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <>
          <Theatre text={text} image2={image2} image3={image3} image={image} />
          <Postanovki stars={star} image={image4} image2={image5} image3={image6} image4={image7}/>
          <Partners gaz={gazprom} />
        </>
      </Layout>
    </>
  )
}

export default Home
